discord.bot.token=${SWGOH_DISCORD_BOT_TOKEN}
discord.owner.token=put-your-authorization-here
discord.default.no_tag_mode=true
discord.default.track_c3po_tb=true
discord.default.track_c3po_tw=true
discord.default.discord_to_tele_broadcast=false
telegram.bot.token=put-your-bot-token-here
mongo.init=${SWGOH_DISCORD_BOT_MONGO_INIT_REQUIRED}
mongo.server.host=${SWGOH_DISCORD_BOT_MONGO_HOST}
mongo.server.port=${SWGOH_DISCORD_BOT_MONGO_PORT}
mongo.db=${SWGOH_DISCORD_BOT_MONGO_DB_NAME}