version: 1
disable_existing_loggers: False

formatters:
  consoleFormatter:
    format: '%(asctime)s | %(levelname)s : %(message)s'
  fileFormatter:
    format: '%(asctime)s | %(levelname)s : %(message)s'

handlers:
  file:
    filename: logs/discord-bot.log
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    formatter: fileFormatter
    maxBytes: 1048576 # 1 MB
    backupCount: 3
  console:
    level: INFO
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: consoleFormatter

loggers:
  root:
    level: DEBUG
    handlers: [ file, console ]