discord.bot.token=${SWGOH_DISCORD_BOT_TOKEN}
discord.default.track_c3po_tb=true
discord.default.track_c3po_tw=true
discord.default.discord_to_tele_broadcast=false
mongo.init=${SWGOH_DISCORD_BOT_MONGO_INIT_REQUIRED}
mongo.server.host=${SWGOH_DISCORD_BOT_MONGO_HOST}
mongo.server.port=${SWGOH_DISCORD_BOT_MONGO_PORT}
mongo.db=${SWGOH_DISCORD_BOT_MONGO_DB_NAME}
discord.listener.log.logger.name=discord-message-listener-logger
discord.listener.log.config.file=log-configs.yaml